/// Generated by AssetsRefGenerator on 2022/07/18

class Res {
  static const String appstore = "assets/images/appstore.png";
  static const String icons = "assets/fonts/icons.ttf";
  static const String jannah = "assets/fonts/jannah.ttf";
  static const String onboard_1 = "assets/images/onboard_1.jpg";
}
